# Generated by Django 5.0.7 on 2024-07-21 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_booksmodel_table_alter_reviewsmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booksmodel',
            table=None,
        ),
        migrations.AlterModelTable(
            name='reviewsmodel',
            table=None,
        ),
    ]
