# Generated by Django 5.0.7 on 2024-07-21 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_booksmodel_table_alter_reviewsmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reviewsmodel',
            table='reviews',
        ),
    ]
